import os
import sys

import re

"""
정규 표현식 (Regular Expression) 이란?
- 문자열 패턴을 탐색하기 위한 수단을 의미한다. (+ 즉, 정규 표현식을 활용하면 문자열로부터 원하는 패턴의 문자열을
손쉽게 탐색하는 것이 가능하다.)

정규 표현식은 문자열 패턴을 탐색하기 위한 여러 기호를 통해 문자열 추출, 치환, 검증 등의 다양한 작업을
처리하는 것이 가능하다.
"""


# Example 17 (정규 표현식)
def start(args):
	"""
	\\ 기호란?
	- Python 명령문이 다음 라인에서 계속 이어진다는 것을 나타내는 기호를 의미한다. (+ 즉, \\ 기호를 활용하면
	명령문을 여러 라인에 걸쳐서 작성하는 것이 가능하다.)
	"""
	oStr = \
	"""
	The images generated by Regexper are commonly referred to as "Railroad Diagrams".
	These diagram are a straight-forward way to illustrate what can sometimes become very complicated processing in a regular expression, with nested looping and optional elements.
	The easiest way to read these diagrams to to start at the left and follow the lines to the right.
	If you encounter a branch, then there is the option of following one of multiple paths (and those paths can loop back to earlier parts of the diagram).
	In order for a string to successfully match the regular expression in a diagram, you must be able to fulfill each part of the diagram as you move from left to right and proceed through the entire diagram to the end.
	"""
